<template><div class="custom-container danger"><p class="custom-container-title">Warning</p>
<p>This page is still under construction.
If you come across any problems please <a href="mailto:florian.langhanki@uni-wuerzburg.de">contact us</a>.</p>
</div>
<h3 id="_3-2project-overview" tabindex="-1"><a class="header-anchor" href="#_3-2project-overview" aria-hidden="true">#</a> 3.2	Project Overview</h3>
<p>Once OCR4all has been opened in a browser, the user will automatically land on the 'Project Overview' starting page. From there, they will be able to access several features:</p>
<ul>
<li>'<strong>Settings</strong>': This feature allows for selecting the book set to be worked on, which can be chosen from the dropdown menu found under ‘Project selection’ – the title having been previously saved as a folder under ocr4all/data/book title (see 1.2). Additionally, the ‘gray’ setting must be selected under the menu point ‘Project image type’.</li>
</ul>
<pre>

BILD BILD

</pre>
<p>fig. 2: Project Overview settings.</p>
<ul>
<li>
<p>Following this initial set up, click on ‘load project’ in order for the book in question to be uploaded to the OCR4all platform. Seeing as OCR4all only accepts certain file designations and formats (i.e. 0001.png etc.), a data conversion might be requested which can be directly carried out in OCR4all (fig. 3).</p>
</li>
<li>
<p>It is irrelevant whether a PDF or individual images were placed in the 'input' folder. If possible, however, single images are usually preferred.</p>
</li>
</ul>
<pre>

BILD BILD

</pre>
<p>fig. 3. Data conversion request (i.g. PDF in 'input' folder).</p>
<ul>
<li>In OCR4all, all data generated during the workflow and for its functioning are saved in a single PageXML file per scan page and are no longer kept in the form of many individual files. If project data from previous versions is still available, it is now possible to convert the project automatically into the structure required by OCR4all.</li>
</ul>
<pre>

BILD BILD

</pre>
<p>fig. 4: possible conversion of a Legacy-Project.</p>
<ul>
<li>The feature &quot;Overview&quot; provides the user with a tabular presentation of the project’s ongoing progress (fig. 4). Each row corresponds to an individual book page, labelled by a page identifier (far left column). The following columns illustrate, from left to right, the workflow’s progression. Once a particular step has been executed, it will appear as completed (green check mark) in that work stage’s specific column.</li>
</ul>
<pre>

BILD BILD

</pre>
<p>fig. 5: Overview.</p>
<ul>
<li>
<p>Clicking on an individual page’s identifier enables the user to check on the state of that specific page’s processing, as well as on the data generated by it, at any time during the workflow. To this effect, please use the ‘images’ column, as well as the subsequent options: ‘original’, ‘binary’, ‘gray’ and ‘noise removal’.</p>
</li>
<li>
<p>With the button &quot;Export GT&quot; (top right) all data created in the course of the project can be exported and packed as a zip folder within 'data'.</p>
</li>
</ul>
</template>
