<template><h4 id="_4-4-1initial-settings" tabindex="-1"><a class="header-anchor" href="#_4-4-1initial-settings" aria-hidden="true">#</a> 4.4.1	Initial Settings</h4>
<ul>
<li>Menu: click on ‘segmentation’, then on ‘LAREX’</li>
<li>Go to ‘Segmentation image type’: select ‘binary’ if you will be working with binarized images, or ‘despeckled’ if the images went through the noise removal process</li>
<li>Click on ‘open LAREX’ → LAREX will open in a new tab</li>
</ul>
<pre>

BILD

</pre>
<p>Abb. 11: LAREX settings.</p>
<p>Once LAREX has opened, the first one of the pre-selected pages will be visible at the centre of your display, including a few initial segmentation results, which are generated by the automatic segmentation each page undergoes when initially opened with LAREX. Please note that these results are not saved. From there, the user will have to adjust the settings, tailoring the initial segmentation results to their particular work’s layout and undertaking a manual post-correction to ensure segmentation accuracy.</p>
<pre>

BILD

</pre>
<p>fig. 12. LAREX interface with automatic segmentation results.</p>
</template>
